### ISSUE TITLE
Error at the end of each ATC_NODE

### ISSUE THREAD

**Issue by hametner** [fabkury/atcd#2]
Hi,
Highly appreciate this webscraping script.
However, I get any error, when executing the code at the end of each ATC_NODE.

<error/vctrs_error_scalar_type>
Error in `vec_size()`:
! `x` must be a vector, not a <xml_nodeset> object.
---
Backtrace:
     ▆
  1. ├─... %>% bind_rows
  2. ├─dplyr::bind_rows(.)
  3. │ └─rlang::list2(...)
  4. ├─base::lapply(...)
  5. │ └─global FUN(X[[i]], ...)
  6. │   ├─sapply(atc_codes, scrape_who_atc) %>% bind_rows
  7. │   └─base::sapply(atc_codes, scrape_who_atc)
  8. │     └─base::lapply(X = X, FUN = FUN, ...)
  9. │       └─global FUN(X[[i]], ...)
 10. │         └─... %>% html_text
 11. ├─dplyr::bind_rows(.)
 12. │ └─rlang::list2(...)
 13. ├─rvest::html_text(.)
 14. │ └─xml2::xml_text(x, trim = trim)
 15. └─dplyr::nth(., 3)
 16.   └─vctrs::vec_size(x)

It seems to be an issue with "nth(., 3)" - however I did not manage to get a workaround.

**Comment by Maria-M-Oliveira** [comment]
I'm getting the same error, but it's not at the same location. Here is my backtrace:
▆
  1. ├─paste0("who_atc_", atc_root) %>% ...
  2. ├─global wrapRDS(., by_name = TRUE, scrape_who_atc(atc_root))
  3. │ └─base::eval(substitute(exprs), envir = new.env(parent = parent.frame(n = 1)))
  4. │   └─base::eval(substitute(exprs), envir = new.env(parent = parent.frame(n = 1)))
  5. │     └─global scrape_who_atc(atc_root)
  6. │       └─... %>% html_text
  7. ├─rvest::html_text(.)
  8. │ └─xml2::xml_text(x, trim = trim)
  9. └─dplyr::nth(., 3)
 10.   └─vctrs::vec_size(x)

**Comment by TheJena** [comment]
Hi @hametner, @Maria-M-Oliveira; I got your very same error

A possible fix is swapping the html_text() and nth(3) in the if statement right below the "# Add root node if needed" comment; i.e., lines
https://github.com/TheJena/WHO-ATC-scraper/blob/16a65dcc142ccebd792de3a98c040b065419b98d/atcd.R#L190 and 
https://github.com/TheJena/WHO-ATC-scraper/blob/16a65dcc142ccebd792de3a98c040b065419b98d/atcd.R#L192 but pay attention to keep the %>% operator in between the two swapped functions

for simplicity I forked the repository and this is the commit of interest https://github.com/TheJena/WHO-ATC-scraper/commit/16a65dcc142ccebd792de3a98c040b065419b98d

**Comment by fabkury** [comment]
Thank you for the report. This bug has been fixed in the latest version I uploaded.
